export interface Patient {
    id?: number,
    fullName: string,
    dateOfBirth: string,
    gender: string,
    maritalStatus: string,    
    countryOfBirth: string,
    cpf: string,
    rg: string,
    phoneNumber: string,
    email: string,
    healthPlanName: string,
    healthPlanNumber: string,
    healthPlanVal: string,
    streetName: string,
    streetNumber: string,
    cep: string,    
    district: string,
    city: string,
    state: string,
    addressComplement: string,
    referencePoint: string,
}
